{% set version = '5.0.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mrmlm
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mrMLM_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mrMLM/mrMLM_{{ version }}.tar.gz
  sha256: 0f2d3e179b52fc2cb3d52c8b83975b20d8d18eaca30f2f87fa3dfbc3eee65b7c

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib('c') }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib('m2w64_c') }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-bedmatrix
    - r-coin >=1.1_0
    - r-data.table
    - r-doparallel
    - r-foreach
    - r-lars
    - r-ncvreg
    - r-rcpp >=0.12.14
    - r-rcppeigen
    - r-sampling
    - r-sbl
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-bedmatrix
    - r-coin >=1.1_0
    - r-data.table
    - r-doparallel
    - r-foreach
    - r-lars
    - r-ncvreg
    - r-rcpp >=0.12.14
    - r-rcppeigen
    - r-sampling
    - r-sbl

test:
  commands:
    - $R -e "library('mrMLM')"           # [not win]
    - "\"%R%\" -e \"library('mrMLM')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=mrMLM
  license: GPL-2.0-or-later
  summary: Conduct multi-locus genome-wide association study under the framework of multi-locus
    random-SNP-effect mixed linear model (mrMLM). First, each marker on the genome is
    scanned. Bonferroni correction is replaced by a less stringent selection criterion
    for significant test. Then, all the markers that are potentially associated with
    the trait are included in a multi-locus genetic model, their effects are estimated
    by empirical Bayes, and all the nonzero effects were further identified by likelihood
    ratio test for significant QTL. The program may run on a desktop or laptop computers.
    If marker genotypes in association mapping population are almost homozygous, these
    methods in this software are very effective. If there are many heterozygous marker
    genotypes, the IIIVmrMLM software is recommended. Wen YJ, Zhang H, Ni YL, Huang
    B, Zhang J, Feng JY, Wang SB, Dunwell JM, Zhang YM, Wu R (2018, <doi:10.1093/bib/bbw145>),
    and Li M, Zhang YW, Zhang ZC, Xiang Y, Liu MH, Zhou YH, Zuo JF, Zhang HQ, Chen Y,
    Zhang YM (2022, <doi:10.1016/j.molp.2022.02.012>).
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: mrMLM
# Type: Package
# Title: Multi-Locus Random-SNP-Effect Mixed Linear Model Tools for GWAS
# Version: 5.0.1
# Date: 2022-3-27
# Maintainer: Yuan-Ming Zhang <soyzhang@mail.hzau.edu.cn>
# Contact: Yuan-Ming Zhang <soyzhang@mail.hzau.edu.cn>
# Authors@R: c( person("Ya-Wen", "Zhang", role="aut") , person("Jing-Tian", "Wang", role="aut") , person("Pei", "Li", role="aut") , person("Yuan-Ming", "Zhang", role=c("aut","cre"), email="soyzhang@mail.hzau.edu.cn", comment=c(ORCID="0000-0003-2317-2190")) )
# Description: Conduct multi-locus genome-wide association study under the framework of multi-locus random-SNP-effect mixed linear model (mrMLM). First, each marker on the genome is scanned. Bonferroni correction is replaced by a less stringent selection criterion for significant test. Then, all the markers that are potentially associated with the trait are included in a multi-locus genetic model, their effects are estimated by empirical Bayes, and all the nonzero effects were further identified by likelihood ratio test for significant QTL. The program may run on a desktop or laptop computers. If marker genotypes in association mapping population are almost homozygous, these methods in this software are very effective. If there are many heterozygous marker genotypes, the IIIVmrMLM software is recommended. Wen YJ, Zhang H, Ni YL, Huang B, Zhang J, Feng JY, Wang SB, Dunwell JM, Zhang YM, Wu R (2018, <doi:10.1093/bib/bbw145>), and Li M, Zhang YW, Zhang ZC, Xiang Y, Liu MH, Zhou YH, Zuo JF, Zhang HQ, Chen Y, Zhang YM (2022, <doi:10.1016/j.molp.2022.02.012>).
# Depends: R (>= 3.5.0),lars
# Imports: Rcpp (>= 0.12.14),methods,foreach,ncvreg,coin(>= 1.1-0),sampling,data.table,doParallel,sbl,BEDMatrix
# License: GPL (>= 2)
# LinkingTo: Rcpp, RcppEigen
# NeedsCompilation: yes
# Packaged: 2022-03-27 08:03:33 UTC; Administrator
# Repository: CRAN
# Date/Publication: 2022-03-27 08:50:02 UTC
# Author: Ya-Wen Zhang [aut], Jing-Tian Wang [aut], Pei Li [aut], Yuan-Ming Zhang [aut, cre] (<https://orcid.org/0000-0003-2317-2190>)
